# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driverservice.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='driverservice.proto',
    package='proto',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n\x13\x64riverservice.proto\x12\x05proto\"C\n\x04User\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tlastlogin\x18\x04 \x01(\x03\"=\n\x08Response\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x0c\n\x04isOK\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"K\n\x0fLocationRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lng\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"G\n\x12GetLocationRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x11\n\tsourceLat\x18\x02 \x01(\x01\x12\x11\n\tsourceLng\x18\x03 \x01(\x01\"`\n\rDriverDetails\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tdriverLat\x18\x04 \x01(\x01\x12\x12\n\ndriverLong\x18\x05 \x01(\x01\x32\xc8\x01\n\rDriverService\x12\x30\n\x0eStoreUserLogin\x12\x0b.proto.User\x1a\x0f.proto.Response\"\x00\x12;\n\x0eUpdateLocation\x12\x16.proto.LocationRequest\x1a\x0f.proto.Response\"\x00\x12H\n\x13GetDriverInLocation\x12\x19.proto.GetLocationRequest\x1a\x14.proto.DriverDetails\"\x00\x62\x06proto3'
)

_USER = _descriptor.Descriptor(
    name='User',
    full_name='proto.User',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='uid', full_name='proto.User.uid', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='email', full_name='proto.User.email', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='name', full_name='proto.User.name', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='lastlogin', full_name='proto.User.lastlogin', index=3,
            number=4, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=30,
    serialized_end=97,
)

_RESPONSE = _descriptor.Descriptor(
    name='Response',
    full_name='proto.Response',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='statusCode', full_name='proto.Response.statusCode', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='isOK', full_name='proto.Response.isOK', index=1,
            number=2, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='message', full_name='proto.Response.message', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=99,
    serialized_end=160,
)

_LOCATIONREQUEST = _descriptor.Descriptor(
    name='LocationRequest',
    full_name='proto.LocationRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='uid', full_name='proto.LocationRequest.uid', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='lat', full_name='proto.LocationRequest.lat', index=1,
            number=2, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='lng', full_name='proto.LocationRequest.lng', index=2,
            number=3, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='timestamp', full_name='proto.LocationRequest.timestamp', index=3,
            number=4, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=162,
    serialized_end=237,
)

_GETLOCATIONREQUEST = _descriptor.Descriptor(
    name='GetLocationRequest',
    full_name='proto.GetLocationRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='uid', full_name='proto.GetLocationRequest.uid', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sourceLat', full_name='proto.GetLocationRequest.sourceLat', index=1,
            number=2, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sourceLng', full_name='proto.GetLocationRequest.sourceLng', index=2,
            number=3, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=239,
    serialized_end=310,
)

_DRIVERDETAILS = _descriptor.Descriptor(
    name='DriverDetails',
    full_name='proto.DriverDetails',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='uid', full_name='proto.DriverDetails.uid', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='email', full_name='proto.DriverDetails.email', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='name', full_name='proto.DriverDetails.name', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='driverLat', full_name='proto.DriverDetails.driverLat', index=3,
            number=4, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='driverLong', full_name='proto.DriverDetails.driverLong', index=4,
            number=5, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=312,
    serialized_end=408,
)

DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['LocationRequest'] = _LOCATIONREQUEST
DESCRIPTOR.message_types_by_name['GetLocationRequest'] = _GETLOCATIONREQUEST
DESCRIPTOR.message_types_by_name['DriverDetails'] = _DRIVERDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
    'DESCRIPTOR': _USER,
    '__module__': 'driverservice_pb2'
    # @@protoc_insertion_point(class_scope:proto.User)
})
_sym_db.RegisterMessage(User)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
    'DESCRIPTOR': _RESPONSE,
    '__module__': 'driverservice_pb2'
    # @@protoc_insertion_point(class_scope:proto.Response)
})
_sym_db.RegisterMessage(Response)

LocationRequest = _reflection.GeneratedProtocolMessageType('LocationRequest', (_message.Message,), {
    'DESCRIPTOR': _LOCATIONREQUEST,
    '__module__': 'driverservice_pb2'
    # @@protoc_insertion_point(class_scope:proto.LocationRequest)
})
_sym_db.RegisterMessage(LocationRequest)

GetLocationRequest = _reflection.GeneratedProtocolMessageType('GetLocationRequest', (_message.Message,), {
    'DESCRIPTOR': _GETLOCATIONREQUEST,
    '__module__': 'driverservice_pb2'
    # @@protoc_insertion_point(class_scope:proto.GetLocationRequest)
})
_sym_db.RegisterMessage(GetLocationRequest)

DriverDetails = _reflection.GeneratedProtocolMessageType('DriverDetails', (_message.Message,), {
    'DESCRIPTOR': _DRIVERDETAILS,
    '__module__': 'driverservice_pb2'
    # @@protoc_insertion_point(class_scope:proto.DriverDetails)
})
_sym_db.RegisterMessage(DriverDetails)

_DRIVERSERVICE = _descriptor.ServiceDescriptor(
    name='DriverService',
    full_name='proto.DriverService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=411,
    serialized_end=611,
    methods=[
        _descriptor.MethodDescriptor(
            name='StoreUserLogin',
            full_name='proto.DriverService.StoreUserLogin',
            index=0,
            containing_service=None,
            input_type=_USER,
            output_type=_RESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='UpdateLocation',
            full_name='proto.DriverService.UpdateLocation',
            index=1,
            containing_service=None,
            input_type=_LOCATIONREQUEST,
            output_type=_RESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='GetDriverInLocation',
            full_name='proto.DriverService.GetDriverInLocation',
            index=2,
            containing_service=None,
            input_type=_GETLOCATIONREQUEST,
            output_type=_DRIVERDETAILS,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_DRIVERSERVICE)

DESCRIPTOR.services_by_name['DriverService'] = _DRIVERSERVICE

# @@protoc_insertion_point(module_scope)
